### ISSUE TITLE
Canonical yml name should be domain

### ISSUE THREAD

**Issue by yuvadm** [yuvadm/namehack.club#56]
In current implementation, there can theoretically be name collisions for identical names on different domains

**Comment by saizai** [comment]
Could you give an example of the conflict? Also, maybe add a template.yml to copy for both candidate and full versions that has instructions of this sort and any others?

**Comment by yuvadm** [comment]
`examp.le` and `exam.ple` can theoretically collide. Not many such names/domains exist, but it's possible.
