### ISSUE TITLE
Create ryanc.yml

### ISSUE THREAD

**Issue by saizai** [yuvadm/namehack.club#60]
For @ryancdotorg

https://github.com/yuvadm/namehack.club/pull/59

@yuvadm maybe should add `candidate: true` until they've personally confirmed?

Also, I can't tell what's going wrong with the merge verification. The new YAML looks fine to me, but seems like the python is choking on it.

**Comment by ryancdotorg** [comment]
Add me if you want, I guess, just don't talk to me about it. I have ignored notifications for this repo.

**Comment by yuvadm** [comment]
Closing the issue, see #59
